### ISSUE TITLE
pokrytie aliased to kavyka?

### ISSUE THREAD

**Issue by pgmmpk** [slavonic/cu-tex#1]
https://github.com/slavonic/cu-tex/blob/master/churchslavic.tra#L115

@typiconman please confirm this translation line. Looks like kavyka and pokrytie are made equivalent. Is this right?

```
\u043d\u2df4\u0487 \u041d\u2df4\ua67c
```

**Comment by typiconman** [comment]
No, that's a mistake. It should be, of course,

`\u043d\u2df4\u0487 \u041d\u2df4\u0487`

**Comment by pgmmpk** [comment]
fixed by commit:

https://github.com/slavonic/cu-tex/commit/3dad3f30d9d396089de279910fde965c10cac3f4
