### ISSUE TITLE
Correctly hyphenate compound words

### ISSUE THREAD

**Issue by typiconman** [slavonic/cu-tex#30]
In a compound word, for example, са́нъ_франці́сскїй, the algorithm needs to know that it is OK to introduce a line break after са́нъ_, and it should _not_ insert an additional hyphen, e.g., not са́нъ__.

Right now, the algorithm gives са́нъ_фран-ці́с-скїй

**Comment by pgmmpk** [comment]
There is a package [`underscore`](https://www.ctan.org/tex-archive/macros/latex/contrib/underscore), that addresses this problem:

```
\usepackage[nohyphen]{underscore}
```

The above is supposed to (1) allow using underscore in text mode and (2) allow hyphenation after underscore (without adding any hyphenation marks).

Internally it just pretends that a compound word is two separate words, connected by zero-width space.

Can you pls check that this solution does work correctly and does not introduce any unwanted side effects?

**Comment by typiconman** [comment]
Yes, I can confirm that it works correctly.

**Comment by typiconman** [comment]
I think we should add a note about this to the documentation, so I will leave this open for now.

**Comment by typiconman** [comment]
Fixed.
