### ISSUE TITLE
Titlo location in numbers

### ISSUE THREAD

**Issue by pgmmpk** [slavonic/cu-tex#32]
CSLTEX supported placement of titlo **between digits** (as a package option `titlonum`). See page 7 of 
[csltex.pdf](https://github.com/slavonic/cu-tex/files/207191/csltex.pdf).

Question: do we need this variant? If yes, what means do we have to control position of titlo combiner?

**Comment by typiconman** [comment]
It is not used in modern Church Slavonic. A titlo between digits or a long titlo over many digits may occur in manuscripts. Positioning of the titlo could be done at the font level in a font intended for working with manuscripts. We would create a second set of anchor points and turn them on using a feature. But currently it is not supported in any of our fonts.

**Comment by pgmmpk** [comment]
Closing - we will not support inter-char titlo positioning.
