### ISSUE TITLE
Position combining letter over two (or more) base glyphs

### ISSUE THREAD

**Issue by typiconman** [slavonic/cu-tex#58]
There is presently no method of positioning a combining character over (between) two glyphs using encoding. It could be done using various hacks at the font level, such as co-opting the Combining Grapheme Joiner (CGJ) and creating a set of right-attaching combining letters. But this is perhaps best done with a LaTeX macro? In the spirit of `\cuKruk`, we could have `\cuSup`, with syntax like this:
`\cuSup{glyph1glyph2}{base1base2}`
which places glyph1glyph2 in a raised position between base1 and base2.

Examples of this behavior can be found in [manuscripts](http://nlr.ru/manuscripts/RA1527/elektronnyiy-katalog?ab=682DE9EA-71DE-4E03-9B06-F30C2A4D69EE).

**Comment by pgmmpk** [comment]
`\cuKruk` has `raise` parameter to control vertical positioning of the kruk symbol. In the same spirit we can add `shift` parameter to move kruk forward (positive) or backward (negative), with default being 0. Or maybe even more fine-grained control over the alignment points in the base glyph (left, center, right)

**Comment by typiconman** [comment]
Is there a way we can compute the midpoint of two glyphs? Take a look at [these examples](http://nlr.ru/manuscripts/dep/img/manuscripts/IzoCatalogue/682DE9EA-71DE-4E03-9B06-F30C2A4D69EE/2.jpg)

**Comment by pgmmpk** [comment]
I think I misunderstood the problem. Goal is to mimic diacritics by placing glyphs on top of symbols, not syllables. For this, re-using `\cuKruk` does not make sense.

I think the simplest would be standard LaTeX means: `base1\cuSup{diacritic}base2`. It will just insert a zero-width symbol between `base1` and `base2`. This has a downside of breaking kerning/ligature between `base1` and `base2` though (I am not aware of any method in LaTeX to compute "midpoint" between two rendered glyphs that would also preserve kerning/ligs).

In the above `cuSup` can be simply defined as `\hbox to 0pt{\hss \raisebox{1em}{dia} \hss}`.

**Comment by typiconman** [comment]
Is it possible to adjust the position of the superscript glyph based on the height of the base glyphs?
![example](https://user-images.githubusercontent.com/5428695/56016249-4aefe980-5d04-11e9-98a1-92ccdbed04d9.png)

**Comment by pgmmpk** [comment]
Yes, its possible. We will need macro to take prev/next characters as a parameter(s). I.e. instead of:
```
AA\cuSup{c}BB
```
it will be like this:
```
A\cuSup{A}{c}{B}B
```
A lazy solution would be to add `raize` option to the base command and adjust height manually when needed

**Comment by pgmmpk** [comment]
Hmm, another idea for the API is to optionally supply height by giving the string, like here:
```
AA\cuSup[AB]{c}BB
```

**Comment by typiconman** [comment]
That looks more intuitive. Since mostly this behavior occurs in Church Slavonic Ustav texts, and most Ustav letters will have the same height, it's rare that we'll need to supply the optional parameters.

**Comment by pgmmpk** [comment]
Here is another possibility:
```
A\textoverset{c}{AB}B
```
where `\textoverset` just places arbitrary string atop of another arbitrary string.

Definition of `\textoverset` is there: https://tex.stackexchange.com/a/42477

**Comment by typiconman** [comment]
The proposed `\textoverset{c}{AB}` doesn't seem to work correctly (too much vertical spacing.
![Screenshot from 2019-04-13 14-13-36](https://user-images.githubusercontent.com/5428695/56078974-97b3ed00-5df6-11e9-9ecf-29c6c7f6db72.png)

**Comment by pgmmpk** [comment]
@typiconman please post the TeX code you used to produce the image above. I hope it can be tweaked to behave more rationally :)

**Comment by typiconman** [comment]
@pgmmpk  Here's an MWE:
```
\documentclass[12pt,a4paper,oneside]{extarticle}
\usepackage{fontspec}
\usepackage{polyglossia}

\setdefaultlanguage{churchslavonic}
\defaultfontfeatures{Mapping=tex-text}
\setromanfont{Menaion Unicode}
\newfontfamily{\cyrillicfont}{Menaion Unicode}
\newfontfamily{\cyrillicfonttt}{Menaion Unicode}
\newcommand\cuSup[2]{%
  \leavevmode
  \vbox{%
    \halign{%
      \hfil##\hfil\cr % center
      \strut#1\cr
      \noalign{\kern-.5ex}
      \strut#2\cr
    }%
  }%
}
\begin{document}
\pagestyle{empty}
\cuSup{ⷧ҇}{мо}
\end{document}
```

**Comment by pgmmpk** [comment]
The problem is that the string you are placing above the base letters contains glyphs that have a lot of empty space on the bottom. One needs to compensate for this by adjusting the raise amount.

In other words, it seem impossible to make both `\cuSup{ⷧ҇}{мо}` and `\cuSup{а}{мо}` to look correct. Because TeX will measure the declared height of a glyph and use it for positioning - it has no clue if declared height actually has content, or glyph content is concentrated on the top of the glyph!

Practically, we can add a parameter that one will have to adjust to make it work nicely with the particular superscripts, e.g.:

```
\cuSup[-1ex]{ⷧ҇}{мо}

\cuSup{а}{мо}
```
This parameter will add to `\kern-.5ex` ...

Am I on the right track?

**Comment by typiconman** [comment]
I think we should make it position superscript (combining) characters by default, and then the optional parameter can be used to position something else.
The following seems to be almost right:
```
\documentclass[12pt,a4paper,oneside]{extarticle}
\usepackage{fontspec}
\usepackage{polyglossia}

\setdefaultlanguage{churchslavonic}
\defaultfontfeatures{Mapping=tex-text}
\setromanfont{Menaion Unicode}
\newfontfamily{\cyrillicfont}{Menaion Unicode}
\newfontfamily{\cyrillicfonttt}{Menaion Unicode}
\newcommand\cuSup[2]{%
  \leavevmode
  \vbox{%
    \halign{%
      \hfil##\hfil\cr % center
      \strut#1\cr
      \noalign{\kern-2.5ex}
      \strut#2\cr
    }%
  }%
}
\begin{document}
\pagestyle{empty}
\cuSup{ⷧ҇}{мо}

\end{document}
```

If someone would like to position ``\cuSup{л}{мо}``, then this won't work.

**Comment by typiconman** [comment]
Fixed and closed.
