### ISSUE TITLE
Travis automatic testing is broken

### ISSUE THREAD

**Issue by pgmmpk** [slavonic/cu-tex#76]

**Comment by typiconman** [comment]
Looks like the whole [Travis CI interface](https://app.travis-ci.com/github/slavonic/cu-tex/branches) is down?

**Comment by pgmmpk** [comment]
GitHub actions is the way to go. I think Travis is obsolete. I'll try to move testing to GitHub actions, time permitting...

**Comment by pgmmpk** [comment]
GitHub actions configured to run test and PDF doc generation on every push, see
https://github.com/slavonic/cu-tex/blob/master/.github/workflows/test.yaml

Closing as fixed

**Comment by typiconman** [comment]
Whoa! Thanks @pgmmpk.
